### ISSUE TITLE
joblib.load error in EmotionFlow.ipynb

### ISSUE THREAD

**Issue by forest1988** [sjmaharjan/emotion_flow#1]
I am interested in your work and try to reproduce the result of "EmotionFlow.ipynb", but I got an error in the dataset loading cell.

```
feature_lst=['nrc_mean_sd_50_all'] 

dataset = Dataset(features=feature_lst, label_extractor='success_genre', genre=False)
```

In my environment, the output is as below.
(I did "git clone" your "emotion_flow" repository under ~/workspace/Clone/ )

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-77a3728d8ed8> in <module>
      1 feature_lst=['nrc_mean_sd_50_all']
      2 
----> 3 dataset = Dataset(features=feature_lst, label_extractor='success_genre', genre=False)

~/workspace/Clone/emotion_flow/code/readers/data_reader.py in __init__(self, features, label_extractor, genre)
     15         self.label_extractor = label_extractor
     16         self.meta_df = pd.read_csv(self.META_DATA, sep='\t', header=0)
---> 17         self.data = self.load_data()
     18         self.use_genre=genre
     19         self.genres=["Fiction", "Science_fiction", "Detective_and_mystery_stories", "Poetry", "Short_stories",

~/workspace/Clone/emotion_flow/code/readers/data_reader.py in load_data(self)
     43 
     44                 if os.path.exists(target_file):
---> 45                     X_train, X_test = joblib.load(target_file)
     46                     train_books, test_books = joblib.load(target_index_file)
     47 

~/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/joblib/numpy_pickle.py in load(filename, mmap_mode)
    583                     return load_compatibility(fobj)
    584 
--> 585                 obj = _unpickle(fobj, filename, mmap_mode)
    586     return obj

~/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/site-packages/joblib/numpy_pickle.py in _unpickle(fobj, filename, mmap_mode)
    502     obj = None
    503     try:
--> 504         obj = unpickler.load()
    505         if unpickler.compat_mode:
    506             warnings.warn("The file '%s' has been generated with a "

~/.pyenv/versions/anaconda3-5.0.1/lib/python3.6/pickle.py in load(self)
   1048                     raise EOFError
   1049                 assert isinstance(key, bytes_types)
-> 1050                 dispatch[key[0]](self)
   1051         except _Stop as stopinst:
   1052             return stopinst.value

KeyError: 118
```

It seems the error occurs while joblib unpickles the vector file.
I suspect this may be caused by the difference in the versions of the libraries used or Python itself.

My environment:
- Python 3.6.10
- Keras 2.2.0 (using Theano backend)
- joblib 0.16.0
- numpy 1.19.1
- pickle.format_version is 4.0

I tried downgrading joblib to some versions, but the same KeyError occurs nevertheless.

Could you please help me overcome this problem?
I'd be grateful if you tell me the environment you used to pickle/unpickle the vector file, or tell me the other way to avoid the problem.

Thank you in advance!

**Comment by sjmaharjan** [comment]
I think the problem is with the pickle files. I think the files got corrupted while uploading. Let me email you the pickle files and trying loading them with `joblib` version of `0.11`.

**Comment by forest1988** [comment]
Thank you for your quick response.
I greatly appreciate your offer. It would be very helpful if you could send me the pickle files.
I will send you an email after this to give you my email address.

**Comment by forest1988** [comment]
Thank you for sending me the email and attached files.
I commented on the issue before checking the email. I'm sorry if it has caused confusion.
I certainly received it. Thank you for looking at my email address.
I will try the files I received from now on.
Thank you again!

**Comment by forest1988** [comment]
I replaced the pickle files with the files you emailed me and it works!
Thank you so much for your quick response.

**Comment by marianaossilva** [comment]
Hi, I'm also very interested in your work and I'm trying to reproduce the results, but in books of Brazilian literature. 
Unfortunately, I'm also getting the same error in the dataset loading cell. 

Would you mind send me the pickle files too?

Thanks in advance and for releasing the code!
